### ISSUE TITLE
Баг в функции RTC::set(const char* compileTimeStamp)

### ISSUE THREAD

**Issue by arkhipovsky** [amperka/TroykaRTC#1]
В строчке 129
_day = ((compileTimeStamp[8] - '0') * 10 + (compileTimeStamp[9] - '0'));
значение compileTimeStamp[8] может быть как цифрой так и пробелом. 
В случае пробела ' '(как это произошло на моем компьютере), переменная _day будет неверна.

**Comment by nkrkv** [comment]
@Igor89 обрати внимание, пожалуйста

**Comment by nomad605dis** [comment]
@arkhipovsky подскажите в каком случае у вас появляется пробел в compileTimeStamp[8]?
